# test
# solved by oh-my-zsh's plugin fzf
# if [ -n "${commands[fzf-share]}" ]; then
#   source "$(fzf-share)/key-bindings.zsh"
#   source "$(fzf-share)/completion.zsh"
# fi

# local ret_status="%(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )"
# PROMPT='${ret_status} %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)'
# RPROMPT="[%*]"
PROMPT='%{$fg[yellow]%}[%D{%H:%M} nix]'$PROMPT

export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

alias ee="echo aa"
